# @format

# Menu
menu:
  主页: /
  归档: /archives
  相册: /gallery
  收藏: /favorite
  #分类: /categories
  标签: /tags
  收集: /postcard
  # 友链: /friends
  关于: /about
# rss: /atom.xml

# Miscellaneous
favicon: /favicon.ico
brand: /images/avator.svg

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ocean/
  # brand: /images/hexo-inverted.png

# MIIT ICP/IP/DOMAIN
beian:
  enable: true
  number: 皖ICP备2024053806号-1
  url: https://beian.miit.gov.cn/
  logo: /images/foot-logo.png
# Tags
# show_count: true

# Toc
toc: true

# 内容
excerpt_link: 阅读全文...

# fancybox
fancybox: true

# 是否显示复制按钮
show_copy_btn: true

# Gitalk
gitalk:
  enable: false # true
  clientID: # GitHub Application Client ID
  clientSecret: # Client Secret
  repo: # Repository name
  owner: # GitHub ID
  admin: # GitHub ID

# Valine
valine:
  enable: false # true
  el: "vcomments"
  appId:
  appKey:
  notify: false
  verify: true
  avatar: "mp"
  pageSize: "5"
  placeholder: "请输入..."

symbols_count_time:
  separated_meta: true # 是否另起一行（true的话不和发表时间等同一行）
  item_text_post: true # 首页文章统计数量前是否显示文字描述（本文字数、阅读时长）
  item_text_total: false # 页面底部统计数量前是否显示文字描述（站点总字数、站点阅读时长）
  awl: 4 # Average Word Length
  wpm: 275 # Words Per Minute（每分钟阅读词数）
  suffix: mins.
